# Generated by Django 3.2.7 on 2021-10-30 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0034_auto_20211030_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='expences',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='expences',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='ledger',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='liabilities',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='liabilities',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
