# Generated by Django 3.2.7 on 2021-10-30 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0035_auto_20211030_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='cash',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='credit',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pcash',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='pcash',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pcredit',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='pcredit',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='preceipt',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='preceipt',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prsales_return',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='prsales_return',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sales_return',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='sales_return',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
