# Generated by Django 3.2.7 on 2021-11-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0036_auto_20211030_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
