# Generated by Django 3.2.7 on 2021-11-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0037_alter_employee_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
