# Generated by Django 3.2.7 on 2021-11-02 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0039_alter_group_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
