# Generated by Django 3.2.7 on 2021-11-02 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0040_alter_group_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_at',
            field=models.DateField(null=True),
        ),
    ]
