# Generated by Django 3.2.7 on 2021-11-07 07:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0041_auto_20211102_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.TextField(max_length=100)),
                ('invoice_no', models.TextField(max_length=100)),
                ('cusomer_id', models.TextField(max_length=100)),
                ('customer_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField(max_length=100)),
                ('customer_id', models.IntegerField()),
                ('invoice_no', models.IntegerField()),
                ('reportDate', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.TextField(max_length=100)),
                ('supplier_name', models.TextField(max_length=100)),
                ('report_date', models.TextField(max_length=100)),
                ('invoice_no', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.TextField(max_length=100)),
                ('supplier_id', models.IntegerField()),
                ('invoice_no', models.IntegerField()),
                ('reportDate', models.DateField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trial_Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('reportdate', models.TextField(max_length=100)),
                ('ledger_id', models.IntegerField()),
                ('ledger_name', models.TextField(max_length=100)),
                ('ledger_category', models.TextField(max_length=100)),
                ('opening_bal', models.TextField(max_length=100)),
                ('debit_amount', models.TextField(max_length=100)),
                ('credit_amount', models.TextField(max_length=100)),
                ('closing_bal', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('name',), 'verbose_name_plural': 'Assets'},
        ),
        migrations.RenameField(
            model_name='cash',
            old_name='amount1',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='cash',
            old_name='price1_1',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='cash',
            old_name='quantity1',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='amount1',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='price1_1',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='quantity1',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='pcash',
            old_name='amount1',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pcash',
            old_name='price1_1',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='pcash',
            old_name='quantity1',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='pcredit',
            old_name='amount1',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pcredit',
            old_name='price1_1',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='pcredit',
            old_name='quantity1',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='prsales_return',
            old_name='amount1',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='prsales_return',
            old_name='price1_1',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='prsales_return',
            old_name='quantity1',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='sales_return',
            old_name='amount1',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='sales_return',
            old_name='price1_1',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='sales_return',
            old_name='quantity2',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_child',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_parent',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='group',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='ledger_statement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ledger_statement',
            name='ledger_id',
        ),
        migrations.RemoveField(
            model_name='ledger_statement',
            name='period',
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sam.asset'),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sam.group'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sam.ledger'),
        ),
        migrations.AddField(
            model_name='ledger_statement',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='ledger_statement',
            name='to_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='ledger_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('id_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sam.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=254, unique=True)),
                ('type', models.CharField(blank=True, default='dynamic', max_length=15, null=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sam.category')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sam.category'),
        ),
    ]
