# Generated by Django 3.2.7 on 2021-11-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0042_auto_20211107_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
