# Generated by Django 3.2.7 on 2021-11-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0043_delete_asset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Invoice',
        ),
    ]
