# Generated by Django 3.2.7 on 2021-11-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0049_demopcash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoPCash',
        ),
    ]
