# Generated by Django 3.2.7 on 2021-11-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0051_demopcash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demopcash',
            name='date',
            field=models.DateField(max_length=100),
        ),
    ]
