# Generated by Django 3.2.7 on 2021-11-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0052_alter_demopcash_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PCredit',
        ),
    ]
