# Generated by Django 3.2.7 on 2021-11-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0056_pcredit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credit',
        ),
    ]
