# Generated by Django 3.2.7 on 2021-11-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0061_auto_20211113_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='date',
            field=models.DateField(max_length=100),
        ),
    ]
