# Generated by Django 3.2.7 on 2021-11-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0062_alter_cash_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledgerStatem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldgr', models.CharField(max_length=50)),
            ],
        ),
    ]
