# Generated by Django 3.2.7 on 2021-11-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0063_ledgerstatem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ledgerStatem',
        ),
    ]
