# Generated by Django 3.2.7 on 2021-11-16 09:40

import Sam.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0065_ledgerstatem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_regno', models.IntegerField()),
                ('app_regdate', models.DateField()),
                ('reg_mobno', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('admin_usernm', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('user_access', models.CharField(max_length=50)),
                ('imag1', models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath)),
                ('imag2', models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath)),
                ('created_at', models.DateField(default=datetime.datetime.now, editable=False)),
            ],
        ),
    ]
