# Generated by Django 3.2.7 on 2021-11-18 07:51

import Sam.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0066_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='credit',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='credit',
            name='due_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath),
        ),
        migrations.AlterField(
            model_name='employee',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath),
        ),
        migrations.AlterField(
            model_name='employee',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath),
        ),
        migrations.AlterField(
            model_name='employee',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath),
        ),
        migrations.AlterField(
            model_name='item',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='imag1',
            field=models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath),
        ),
        migrations.AlterField(
            model_name='job',
            name='imag2',
            field=models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath),
        ),
        migrations.AlterField(
            model_name='job',
            name='imag3',
            field=models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath),
        ),
        migrations.AlterField(
            model_name='job',
            name='imag4',
            field=models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='ledger_statement',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='pcash',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='pcredit',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='preceipt',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='prsales_return',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='sales_return',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterModelTable(
            name='item',
            table='sam_item',
        ),
    ]
