# Generated by Django 3.2.7 on 2021-11-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0067_auto_20211118_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_return',
            name='date',
            field=models.DateField(),
        ),
    ]
