# Generated by Django 3.2.7 on 2021-11-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0068_alter_sales_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='due_on',
            field=models.DateField(),
        ),
    ]
