# Generated by Django 3.2.7 on 2021-11-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0069_auto_20211118_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcash',
            name='date',
            field=models.DateField(),
        ),
    ]
