# Generated by Django 3.2.7 on 2021-11-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0070_alter_pcash_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcredit',
            name='due_on',
            field=models.DateField(),
        ),
    ]
