# Generated by Django 3.2.7 on 2021-11-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0071_alter_pcredit_due_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prsales_return',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prsales_return',
            name='due_on',
            field=models.DateField(),
        ),
    ]
