# Generated by Django 3.2.7 on 2021-11-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0073_auto_20211118_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial_balance',
            name='date',
            field=models.DateField(),
        ),
    ]
